server:
  port: 8083

spring:
  application:
    name: api-gateway
#  config:
#    import: optional:configserver:http://localhost:8088
  cloud:
    gateway:
      routes:
        - id: serviceA
          uri: lb://serviceA
          predicates:
            - Path=/api/a/**
        - id: serviceB
          uri: lb://serviceB
          predicates:
            - Path=/api/b/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#management:
#  tracing:
#    sampling:
#      probability: 1.0